fix: workflow
- ajout d'un test pour l'endpoint

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,7 +36,10 @@ jobs:
       run: docker run --rm -d -p 8080:80 --name test-app ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
 
     - name: Test API Endpoint
-      run: curl http://localhost:8080/ || (echo "API test failed" && exit 1)
+      run: |
+        sleep 5  # Attendre que le conteneur démarre complètement
+        curl http://localhost:8080/ || (docker logs test-app && echo "API test failed" && exit 1)
+
 
     - name: Stop and Remove Test Container
       run: docker stop test-app
