fix: workflow
- fix deplaoy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,17 +28,27 @@ jobs:
       run: |
         echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
-    # Étape 4 : Construire et envoyer l'image Docker
-    - name: Build and Push Docker Image
-      run: |
-        docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ./api
-        docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
+    # Étape 4 : Construire et tester l'image Docker localement
+    - name: Build Docker Image
+      run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ./api
 
-    # Étape 5 : Déployer l'image Docker sur Azure App Service avec le Publish Profile
+    - name: Test Docker Image Locally
+      run: docker run --rm -d -p 8080:80 --name test-app ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
+
+    - name: Test API Endpoint
+      run: curl http://localhost:8080/ || (echo "API test failed" && exit 1)
+
+    - name: Stop and Remove Test Container
+      run: docker stop test-app
+
+    # Étape 5 : Pousser l'image Docker
+    - name: Push Docker Image
+      run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
+
+    # Étape 6 : Déployer l'image Docker sur Azure App Service
     - name: Deploy to Azure Web App
       uses: azure/webapps-deploy@v2
       with:
-        app-name: shop-app-app 
-        slot-name: production
+        app-name: shop-app-app
         images: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
